[project]
name = "meso-forge-consumer-example"
version = "0.1.0"
description = "Example project consuming packages from local MinIO channel"
authors = ["Your Name <your.email@example.com>"]
channels = [
    "conda-forge",
    "https://prefix.dev/meso-forge",
    "http://localhost:19000/pixi-local/meso-forge"
]
platforms = ["linux-64", "linux-aarch64"]

[dependencies]
# Install packages from your local MinIO channel
meso-forge = "*"
minio-s3-tools = "*"

# Standard dependencies from conda-forge
python = ">=3.9"
nushell = ">=0.105.1"

# Test that packages are installed and working
[tasks.test-install]
cmd = "meso-forge help"

[tasks.test-minio]
cmd = "manage-minio-credentials --help"

# Example build task using your tooling
[tasks.build-example]
cmd = ["bash", "-c", "echo 'Using meso-forge from local channel' && meso-forge help"]

# List available packages
[tasks.list-packages]
cmd = "meso-forge version-update --list-packages"

[feature.dev.dependencies]
# Development dependencies
git = "*"

[environments]
default = { solve-group = "default" }
dev = { features = ["dev"], solve-group = "dev" }
