[workspace]
authors = ["Fredrick Eisele <fred.eisele@vanderbilt.edu>"]
channels = ["https://prefix.dev/meso-forge", "conda-forge"]
name = "meso-forge-tools"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
