# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.2.1"

package:
  name: meso-forge-tooling
  version: ${{ version }}

source:
  path: ../../

build:
  number: 0
  noarch: generic
  script:
    interpreter: bash
    content: |
      # Create the tooling directory structure
      mkdir -p $PREFIX/share/meso-forge-tooling

      # Copy all tooling components
      cp -r meso-forge-tooling/scripts $PREFIX/share/meso-forge-tooling/
      cp -r meso-forge-tooling/pkg-skeletons $PREFIX/share/meso-forge-tooling/

      # Copy configuration files
      cp meso-forge-tooling/configs/pixi.toml $PREFIX/share/meso-forge-tooling/
      cp meso-forge-tooling/configs/conda-forge.yml $PREFIX/share/meso-forge-tooling/
      cp meso-forge-tooling/configs/auth.json.example $PREFIX/share/meso-forge-tooling/

      # Copy documentation
      cp meso-forge-tooling/docs $PREFIX/share/meso-forge-tooling/ -r
      cp common/README.adoc $PREFIX/share/meso-forge-tooling/
      cp common/LICENSE.txt $PREFIX/share/meso-forge-tooling/

      # Create wrapper scripts for meso-forge command
      mkdir -p $PREFIX/bin

      # Install the nushell wrapper script
      cp meso-forge-tooling/scripts/meso-forge.nu $PREFIX/bin/meso-forge.nu
      chmod +x $PREFIX/bin/meso-forge.nu

      # Create bash shim that calls the nushell version
      cat > $PREFIX/bin/meso-forge << 'EOF'
      #!/bin/bash
      # meso-forge - Bash shim for nushell wrapper
      exec nu "$CONDA_PREFIX/bin/meso-forge.nu" "$@"
      EOF
      chmod +x $PREFIX/bin/meso-forge

      # Install pixi task management wrapper - copy the original
      cp meso-forge-tooling/scripts/pixi_tasks_manage.nu $PREFIX/bin/pixi-tasks.nu
      chmod +x $PREFIX/bin/pixi-tasks.nu

      # Create bash shim for pixi task management that sets NU_LIB_DIRS and copies module
      cat > $PREFIX/bin/pixi-tasks << 'EOF'
      #!/bin/bash
      # pixi-tasks - Bash shim for pixi task management
      # Create a temporary directory and copy the module there for relative import
      TEMP_DIR=$(mktemp -d)
      cp "$CONDA_PREFIX/share/meso-forge-tooling/scripts/pixi_tasks_mod.nu" "$TEMP_DIR/"
      cp "$CONDA_PREFIX/bin/pixi-tasks.nu" "$TEMP_DIR/"
      cd "$TEMP_DIR"
      nu "pixi_tasks_manage.nu" "$@"
      cd - > /dev/null
      rm -rf "$TEMP_DIR"
      EOF
      chmod +x $PREFIX/bin/pixi-tasks

      # Create environment activation script
      mkdir -p $PREFIX/etc/conda/activate.d
      cat > $PREFIX/etc/conda/activate.d/meso-forge-tooling.sh << 'EOF'
      export MESO_FORGE_TOOLING_ROOT="$CONDA_PREFIX/share/meso-forge-tooling"
      export MESO_FORGE_VERSION="0.2.1"
      # Set NU_LIB_DIRS to include meso-forge-tooling scripts for module resolution
      export NU_LIB_DIRS="${NU_LIB_DIRS:+$NU_LIB_DIRS:}$CONDA_PREFIX/share/meso-forge-tooling/scripts"
      EOF

requirements:
  host:
    - python >=3.9
  run:
    - nushell >=0.105.1
    - rattler-build >=0.40.0
    - rattler-index >=0.22.4
    - git >=2.49.0
    - python >=3.9
    - pyyaml >=6.0.2
    - typer >=0.16.0
    - requests >=2.32.3
    - ruamel.yaml >=0.17.0
    - semver >=3.0.2

tests:
  - script:
      interpreter: bash
      content: |
        # Source the conda activation script to set up environment
        source "$CONDA_PREFIX/etc/conda/activate.d/meso-forge-tooling.sh"

        # Test that the meso-forge command is available
        meso-forge help

        # Test that tooling files are accessible
        test -d "$CONDA_PREFIX/share/meso-forge-tooling/scripts"
        test -d "$CONDA_PREFIX/share/meso-forge-tooling/pkg-skeletons"

        # Test that required files exist
        test -f "$CONDA_PREFIX/share/meso-forge-tooling/pixi.toml"
        test -f "$CONDA_PREFIX/share/meso-forge-tooling/README.adoc"
        test -f "$CONDA_PREFIX/share/meso-forge-tooling/docs/pixi-task-management.adoc"

        # Test pixi task management tools
        test -f "$CONDA_PREFIX/bin/pixi-tasks.nu"
        test -f "$CONDA_PREFIX/bin/pixi-tasks"
        pixi-tasks help

        # Test that environment variables are set
        test -n "$MESO_FORGE_TOOLING_ROOT"
        test -n "$MESO_FORGE_VERSION"

        echo "All meso-forge-tooling tests passed!"

about:
  homepage: https://github.com/phreed/meso-forge
  repository: https://github.com/phreed/meso-forge
  documentation: https://github.com/phreed/meso-forge/blob/main/README.adoc
  license: MIT
  license_file: common/LICENSE.txt
  summary: Multi-package build suite for conda packages
  description: |
    meso-forge-tooling provides the complete build infrastructure for creating
    and maintaining conda packages across multiple domains. It includes:

    - Build scripts and utilities (Nu shell based)
    - Package templates and skeletons for multiple languages
    - Publishing infrastructure for conda channels
    - Testing and validation tools
    - Version management utilities
    - Linting and quality assurance tools
    - Pixi task management for integrating meso-forge into existing projects

    This tooling package is designed to be used by domain-specific package
    repositories, providing a consistent build experience across different
    package categories while allowing for domain-specific customization.

    The tooling supports building packages for multiple languages including
    Python, Rust, C++, Go, JavaScript, R, Ruby, and JVM-based languages.

extra:
  recipe-maintainers:
    - phreed
